name: Docker build

on:
  push:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin

      - name: Build image
        run: docker build -t docker.pkg.github.com/${{ github.repository }} --build-arg NPM_TOKEN=${{ secrets.NPM_TOKEN }} .

      - name: Push image
        run: docker push docker.pkg.github.com/${{ github.repository }}
